#!/usr/bin/env python3
"""
Stage 5 — call sheets. One page per prospect, for Grace and Javid.

The dossier is the product; messages are a by-product (doc 02). Each sheet carries
the signal, the evidence, and the arithmetic to compute LIVE with the owner.

    python 05_callsheets.py --in out/scored.jsonl --out out/callsheets.md --top 25
"""
from __future__ import annotations
import argparse, json
from pathlib import Path

# Doc 07 §2.1: the $75K/month figure is a CEILING, not a median. Compute in front
# of the prospect from their own numbers instead of asserting the headline.
ARITHMETIC = {
    "auto_repair": (
        "Typical shop your size takes 25-45 calls/day. Industry data says 20-30% get "
        "missed, and 85% of people who hit voicemail never call back. At your average "
        "repair order that is $X/month walking away. ASK THEM their call volume and "
        "average RO — do the maths together. Never quote $75,000."
    ),
    "collision": (
        "Claims are down, more than 1 in 4 drivers now carry $1,000+ deductibles, and "
        "shops that build their own lead channels get higher ARO and better negotiating "
        "position with insurers. ASK: what share of work still comes from DRP referrals?"
    ),
    "med_spa": (
        "Patient LTV runs $1,800-5,200 over 12 months. If 30-50% of the base is dormant, "
        "reactivating even 20 patients is $36-104K. And Boulevard cannot show which "
        "campaigns drove revenue. ASK: how many patients haven't been back in 12 months?"
    ),
    "plumbing": (
        "Emergency calls carry $150-250 surcharges and arrive outside business hours. A "
        "missed 2am burst-pipe call is a lost $500-2,000 job. ASK: who answers at 9pm?"
    ),
    "hvac": (
        "Each missed call costs roughly $350 in immediate lost revenue — published in "
        "your own trade press. Five a week is $91,000 a year. ASK: how many calls come "
        "in on the hottest day of the month, and who picks up?"
    ),
}


def sheet(r: dict, rank: int) -> str:
    s = r.get("signals") or {}
    L = [
        f"## {rank}. {r.get('name','(unnamed)')}",
        "",
        f"**Score {r['score']}**  ·  pain {r['pain']} × pay {r['pay']} × reach {r['reach']}  "
        f"·  {r.get('vertical')}  ·  Division {r.get('division')}",
        f"**Lead with:** {r.get('lead_product')}",
        "",
        "| | |",
        "|---|---|",
        f"| Phone | **{r.get('phone_e164') or r.get('phone','?')}** ({r.get('line_type','?')}) |",
        f"| Website | {r.get('site','—')} |",
        f"| Address | {r.get('full_address') or r.get('address','—')} |",
        f"| Reviews | {r.get('reviews','?')} · rating {r.get('rating','?')} |",
        f"| Locations | {r.get('location_count',1)} |",
    ]
    if r.get("owner_name"):
        L.append(f"| Owner | {r['owner_name']} |")
    if s.get("claimed_customer_count"):
        L.append(f"| Claims | {s['volume_claim_text']} |")
    if s.get("booking_platforms"):
        L.append(f"| Software | {', '.join(s['booking_platforms'])} |")

    L += ["", "**Why this prospect — say the true thing, then ask a question:**"]
    for w in r["why"]["pain"]:
        L.append(f"- {w}")

    L += ["", "**The arithmetic — compute it WITH them, don't assert it:**", "",
          f"> {ARITHMETIC.get(r.get('vertical',''), 'ASK what their volume is first.')}"]

    verify = []
    if s.get("claims_247"):
        verify.append("Site claims 24/7 — **call after hours and confirm before using this**")
    if r["facts"].get("no_online_booking"):
        verify.append("No online booking found — confirm by loading the site")
    if s.get("stale_copyright") and s.get("copyright_year"):
        verify.append(f"Copyright reads {s['copyright_year']} — verify it's really stale")
    if verify:
        L += ["", "**VERIFY BEFORE YOU SAY IT** (a false signal is worse than a generic call "
              "— it proves we didn't look):"]
        L += [f"- [ ] {v}" for v in verify]

    L += ["", "**Compliance:** DNC-scrubbed? `[ ]`  ·  Manual dial only — no power dialer on "
          "this number  ·  No SMS until written opt-in captured", "", "---", ""]
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="inp", required=True)
    ap.add_argument("--out", dest="out", required=True)
    ap.add_argument("--top", type=int, default=25)
    a = ap.parse_args()

    recs = [json.loads(l) for l in Path(a.inp).read_text().splitlines() if l.strip()]
    kept = [r for r in recs if not r.get("dropped")][: a.top]

    head = [
        f"# Call sheets — top {len(kept)}", "",
        "Generated by `pipeline/05_callsheets.py`. **Every signal below is machine-detected "
        "and unverified.** Confirm anything you plan to say out loud.", "",
        "**Before dialling:** DNC scrub (national + state), manual dial only — the TCPA "
        "applies to mobiles even in B2B. See `prospecting/11-contact-data-stack.md` §1.", "",
        "---", "",
    ]
    Path(a.out).write_text("\n".join(head) + "\n".join(sheet(r, i) for i, r in enumerate(kept, 1)))
    print(f"wrote {len(kept)} call sheets -> {a.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main()) if (sys := __import__("sys")) else None
